[package]
name = "file-store-bucket"
version = "0.1.0"
description = "A shareable Motoko canister for storing files."
repository = "https://github.com/IC-DAPPS/BitcoinUSTbills/tree/main/packages/file-store-bucket"

[dependencies]
base = "0.11.1"
sha2 = "0.0.6"
# Add any other Motoko dependencies here, for example:
# base = "0.10.2"
