name: Publish Motoko Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-docs:
    name: Build and publish Motoko docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 0.28.0

      - name: Build documentation
        run: |
          echo "Using mo-doc from DFX cache..."
          echo "DFX cache location: $(dfx cache show)"
          echo "mo-doc path: $(dfx cache show)/mo-doc"

          # Use the correct mo-doc path from DFX cache
          "$(dfx cache show)/mo-doc" --source packages/file-store-bucket/src --output packages/file-store-bucket/docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload docs to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/file-store-bucket/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
