name: Publish Motoko Docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-docs:
    name: Build and publish Motoko docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 0.28.0

      - name: Build documentation
        run: |
          # Find mo-doc in DFX installation
          MO_DOC_PATH=$(find $HOME -name "mo-doc" -type f 2>/dev/null | head -1)
          if [ -z "$MO_DOC_PATH" ]; then
            echo "mo-doc not found, trying alternative paths..."
            # Try common DFX installation paths
            for path in "$HOME/.local/share/dfx/bin/mo-doc" "$HOME/bin/mo-doc" "/usr/local/bin/mo-doc"; do
              if [ -f "$path" ]; then
                MO_DOC_PATH="$path"
                break
              fi
            done
          fi

          if [ -z "$MO_DOC_PATH" ]; then
            echo "Error: mo-doc not found in any expected location"
            exit 1
          fi

          echo "Using mo-doc at: $MO_DOC_PATH"
          "$MO_DOC_PATH" --source packages/file-store-bucket/src --output packages/file-store-bucket/docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload docs to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/file-store-bucket/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
